global:
  - CC_TEST_REPORTER_ID=CC_TEST_REPORTER_ID

language: ruby
bundler_args: --deployment --without development
cache: bundler
sudo: required

rvm:
  - 2.6.5

before_install:
  - gem update --system
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-linux-amd64.zip -O /tmp/gnatsd.zip
  - unzip /tmp/gnatsd.zip
  - export PATH=$PATH:$PWD/gnatsd-v0.9.4-linux-amd64

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake $TASKS

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT